baseURL = 'https://Wsy2006-51.github.io/'
languageCode = 'zh-cn'
title = 'Whimsy的温暖小屋'
theme = 'PaperMod'

[markup.highlight]
style = "monokai"
lineNos = true

# 所有的全局参数都放在这里
[params]
math = true
author = "Zephyr_Whimsy"  # 确保这行在这里

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 1

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 2